version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CloudResumeChallenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-whvhm165hy7e"
s3_prefix = "CloudResumeChallenge"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=648065499017.dkr.ecr.us-east-2.amazonaws.com/cloudresumechallengee56d0e94/helloworldfunction19d43fc4repo"]
